### ISSUE TITLE
http://jscompress.com/

### ISSUE THREAD

**Issue by laviniu** [vlucas/jscompress.com#2]
&amp;quot; is converted to "

example

function vaca()
{
	el.find(".c-links .c-mini-tooltip-ico").tooltip({content: 'The  &amp;quot;Edit as new &amp;quot; feature creates a copy of the current item and opens it for editing.<br /> Don\'t forget to Save/Publish it after editing. The current item remains unchanged.', className: 'c-tooltip', width: '415'});
}

**Comment by eliercm** [comment]
Hello,

I've been using this services for a long time and now I'm experimenting weird behavior. When I try to compress a long JS file I get "500 Internal Server Error" screen. The service is working because I used it to compress a short JS snippet and It works, the problem is when I put a big piece of code.

I'm using the "Copy & Paste Javascript Code" section.

Please help.

Thanks

**Comment by vlucas** [comment]
@eliercm Yours sounds like a separate issue. Can you make a Gist of the code you were trying to paste in so I can see what is happening?

**Comment by eliercm** [comment]
@vlucas 
I can't do that. But the code works, I also tried another JS file that wasn't modified and I got the same error. Like I said in my previous comment, I've compressed those files in the same way before.
Thanks for the response.

**Comment by vlucas** [comment]
@eliercm your 500 error issues should be resolved now. Thanks.

**Comment by eliercm** [comment]
Hello,

Thank you for the update, It's working fine again. I'm sorry for my late
response.

Regards,
Elier

**Comment by vlucas** [comment]
This has been fixed with the new rewrite in React.js: http://jscompress.com/
